spring.application.name=spring-boot-prevent-post
spring.data.redis.host = localhost
spring.data.redis.port = 6379
spring.data.redis.timeout = 2s

spring.datasource.url = jdbc:mysql://localhost:3306/mydb
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto: validate
spring.jpa.open-in-view: false


